<?php
namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class SeedDataAnime extends Seeder
{
    public function run()
    {
        $data = [
            [
                'title' => 'One Piece',
                'japanese_title' => 'ワンピース',
                'poster' => 'p-one-piece.jpg',
                'navbar_cover' => 'n-one-piece.jpg',
                'genre' => 'Adventure, Comedy, Fantasy',
                'score' => 8.8,
                'type' => 'TV',
                'status' => 'Ongoing',
                'total_episode' => 1070,
                'duration' => '24 min per ep',
                'release_date' => '1999-10-20',
                'studio' => 'Toei Animation',
                'producer' => 'Fuji TV',
                'synopsis' => 'A pirate sets out to find the greatest treasure and become the Pirate King.'
            ],
            [
                'title' => 'My Hero Academia',
                'japanese_title' => '僕のヒーローアカデミア',
                'poster' => 'p-my-hero-academia.jpg',
                'navbar_cover' => 'n-my-hero-academia.jpg',
                'genre' => 'Action, Comedy, Super Power',
                'score' => 8.3,
                'type' => 'TV',
                'status' => 'Ongoing',
                'total_episode' => 138,
                'duration' => '24 min per ep',
                'release_date' => '2016-04-03',
                'studio' => 'Bones',
                'producer' => 'TOHO animation',
                'synopsis' => 'In a world where superpowers are common, a boy dreams of becoming the greatest hero.'
            ],
            [
                'title' => 'Demon Slayer: Kimetsu no Yaiba',
                'japanese_title' => '鬼滅の刃',
                'poster' => 'p-demon-slayer.jpg',
                'navbar_cover' => 'n-demon-slayer.jpg',
                'genre' => 'Action, Demons, Historical',
                'score' => 8.9,
                'type' => 'TV',
                'status' => 'Ongoing',
                'total_episode' => 26,
                'duration' => '24 min per ep',
                'release_date' => '2019-04-06',
                'studio' => 'ufotable',
                'producer' => 'Aniplex',
                'synopsis' => 'A young boy joins a secret group of demon hunters after his family is slaughtered.'
            ],
            [
                'title' => 'Attack on Titan',
                'japanese_title' => '進撃の巨人',
                'poster' => 'p-attack-on-titan.jpg',
                'navbar_cover' => 'n-attack-on-titan.jpg',
                'genre' => 'Action, Drama, Fantasy',
                'score' => 9.1,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 75,
                'duration' => '24 min per ep',
                'release_date' => '2013-04-07',
                'studio' => 'Wit Studio',
                'producer' => 'Production I.G',
                'synopsis' => 'Humanity fights against man-eating giants known as Titans in a desperate struggle for survival.'
            ],
            [
                'title' => 'Naruto',
                'japanese_title' => 'ナルト',
                'poster' => 'p-naruto.jpg',
                'navbar_cover' => 'n-naruto.jpg',
                'genre' => 'Action, Adventure, Super Power',
                'score' => 7.9,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 220,
                'duration' => '23 min per ep',
                'release_date' => '2002-10-03',
                'studio' => 'Pierrot',
                'producer' => 'TV Tokyo',
                'synopsis' => 'A young ninja strives to achieve his dream of becoming the strongest ninja leader.'
            ],
            [
                'title' => 'Death Note',
                'japanese_title' => 'デスノート',
                'poster' => 'p-death-note.jpg',
                'navbar_cover' => 'n-death-note.jpg',
                'genre' => 'Mystery, Supernatural, Thriller',
                'score' => 9.0,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 37,
                'duration' => '23 min per ep',
                'release_date' => '2006-10-04',
                'studio' => 'Madhouse',
                'producer' => 'VAP',
                'synopsis' => 'A high school student gains a notebook that allows him to kill anyone whose name he writes in it.'
            ],
            [
                'title' => 'Fullmetal Alchemist: Brotherhood',
                'japanese_title' => '鋼の錬金術師 FULLMETAL ALCHEMIST',
                'poster' => 'p-fullmetal-alchemist.jpg',
                'navbar_cover' => 'n-fullmetal-alchemist.jpg',
                'genre' => 'Action, Adventure, Fantasy',
                'score' => 9.2,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 64,
                'duration' => '24 min per ep',
                'release_date' => '2009-04-05',
                'studio' => 'Bones',
                'producer' => 'Aniplex',
                'synopsis' => 'Two brothers use alchemy to search for the Philosopher\'s Stone to restore their bodies.'
            ],
            [
                'title' => 'Sword Art Online',
                'japanese_title' => 'ソードアート・オンライン',
                'poster' => 'p-sword-art-online.jpg',
                'navbar_cover' => 'n-sword-art-online.jpg',
                'genre' => 'Action, Adventure, Fantasy',
                'score' => 7.5,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 25,
                'duration' => '23 min per ep',
                'release_date' => '2012-07-08',
                'studio' => 'A-1 Pictures',
                'producer' => 'Aniplex',
                'synopsis' => 'Players are trapped in a virtual reality game and must fight to survive.'
            ],
            [
                'title' => 'Code Geass: Lelouch of the Rebellion',
                'japanese_title' => 'コードギアス 反逆のルルーシュ',
                'poster' => 'p-code-geass.jpg',
                'navbar_cover' => 'n-code-geass.jpg',
                'genre' => 'Action, Drama, Mecha',
                'score' => 8.7,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 25,
                'duration' => '24 min per ep',
                'release_date' => '2006-10-06',
                'studio' => 'Sunrise',
                'producer' => 'Bandai Visual',
                'synopsis' => 'A brilliant exiled prince gains the power to control anyone and sets out to overthrow a tyrannical empire.'
            ],
            [
                'title' => 'Jujutsu Kaisen',
                'japanese_title' => '呪術廻戦',
                'poster' => 'p-jujutsu-kaisen.jpg',
                'navbar_cover' => 'n-jujutsu-kaisen.jpg',
                'genre' => 'Action, Supernatural, Fantasy',
                'score' => 8.7,
                'type' => 'TV',
                'status' => 'Ongoing',
                'total_episode' => 24,
                'duration' => '23 min per ep',
                'release_date' => '2020-10-03',
                'studio' => 'MAPPA',
                'producer' => 'Toho Animation',
                'synopsis' => 'A high school student becomes a vessel for a powerful curse and fights against supernatural beings.'
            ],
            [
                'title' => 'Tokyo Ghoul',
                'japanese_title' => '東京喰種トーキョーグール',
                'poster' => 'p-tokyo-ghoul.jpg',
                'navbar_cover' => 'n-tokyo-ghoul.jpg',
                'genre' => 'Action, Horror, Supernatural',
                'score' => 7.9,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 12,
                'duration' => '24 min per ep',
                'release_date' => '2014-07-04',
                'studio' => 'Pierrot',
                'producer' => 'Marvelous AQL',
                'synopsis' => 'A college student is transformed into a half-ghoul after a deadly encounter.'
            ],
            [
                'title' => 'Hunter x Hunter',
                'japanese_title' => 'ハンター×ハンター',
                'poster' => 'p-hunter-x-hunter.jpg',
                'navbar_cover' => 'n-hunter-x-hunter.jpg',
                'genre' => 'Action, Adventure, Fantasy',
                'score' => 9.1,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 148,
                'duration' => '23 min per ep',
                'release_date' => '2011-10-02',
                'studio' => 'Madhouse',
                'producer' => 'VAP',
                'synopsis' => 'A young boy embarks on a journey to find his father and becomes a Hunter.'
            ],
            [
                'title' => 'Bleach',
                'japanese_title' => 'ブリーチ',
                'poster' => 'p-bleach.jpg',
                'navbar_cover' => 'n-bleach.jpg',
                'genre' => 'Action, Adventure, Super Power',
                'score' => 8.1,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 366,
                'duration' => '24 min per ep',
                'release_date' => '2004-10-05',
                'studio' => 'Pierrot',
                'producer' => 'TV Tokyo',
                'synopsis' => 'A teenager gains Soul Reaper powers and defends humans from evil spirits.'
            ],
            [
                'title' => 'Black Clover',
                'japanese_title' => 'ブラッククローバー',
                'poster' => 'p-black-clover.jpg',
                'navbar_cover' => 'n-black-clover.jpg',
                'genre' => 'Action, Comedy, Fantasy',
                'score' => 8.3,
                'type' => 'TV',
                'status' => 'Ongoing',
                'total_episode' => 170,
                'duration' => '23 min per ep',
                'release_date' => '2017-10-03',
                'studio' => 'Pierrot',
                'producer' => 'TV Tokyo',
                'synopsis' => 'Two orphans aspire to become the Wizard King in a magical world.'
            ],
            [
                'title' => 'Fairy Tail',
                'japanese_title' => 'フェアリーテイル',
                'poster' => 'p-fairy-tail.jpg',
                'navbar_cover' => 'n-fairy-tail.jpg',
                'genre' => 'Action, Adventure, Comedy',
                'score' => 7.8,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 328,
                'duration' => '24 min per ep',
                'release_date' => '2009-10-12',
                'studio' => 'A-1 Pictures',
                'producer' => 'TV Tokyo',
                'synopsis' => 'A young mage joins a guild known for its chaotic behavior and powerful magic.'
            ],
            [
                'title' => 'Re:Zero - Starting Life in Another World',
                'japanese_title' => 'Re: ゼロから始める異世界生活',
                'poster' => 'p-re-zero.jpg',
                'navbar_cover' => 'n-re-zero.jpg',
                'genre' => 'Drama, Fantasy, Thriller',
                'score' => 8.5,
                'type' => 'TV',
                'status' => 'Ongoing',
                'total_episode' => 50,
                'duration' => '25 min per ep',
                'release_date' => '2016-04-04',
                'studio' => 'White Fox',
                'producer' => 'Kadokawa',
                'synopsis' => 'A boy is transported to another world and finds himself in a time loop.'
            ],
            [
                'title' => 'Your Lie in April',
                'japanese_title' => '四月は君の嘘',
                'poster' => 'p-your-lie-in-april.jpg',
                'navbar_cover' => 'n-your-lie-in-april.jpg',
                'genre' => 'Drama, Romance, Music',
                'score' => 8.7,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 22,
                'duration' => '22 min per ep',
                'release_date' => '2014-10-10',
                'studio' => 'A-1 Pictures',
                'producer' => 'Aniplex',
                'synopsis' => 'A young pianist rediscovers his love for music after meeting a spirited violinist.'
            ],
            [
                'title' => 'Haikyuu!!',
                'japanese_title' => 'ハイキュー!!',
                'poster' => 'p-haikyuu.jpg',
                'navbar_cover' => 'n-haikyuu.jpg',
                'genre' => 'Sports, Drama, Comedy',
                'score' => 8.7,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 85,
                'duration' => '24 min per ep',
                'release_date' => '2014-04-06',
                'studio' => 'Production I.G',
                'producer' => 'TOHO animation',
                'synopsis' => 'A determined boy with a love for volleyball aims to excel in a competitive team.'
            ],
            [
                'title' => 'Clannad: After Story',
                'japanese_title' => 'クラナド アフターストーリー',
                'poster' => 'p-clannad-after-story.jpg',
                'navbar_cover' => 'n-clannad-after-story.jpg',
                'genre' => 'Drama, Romance, Slice of Life',
                'score' => 9.0,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 24,
                'duration' => '24 min per ep',
                'release_date' => '2008-10-03',
                'studio' => 'Kyoto Animation',
                'producer' => 'Pony Canyon',
                'synopsis' => 'The heartfelt story of a couple facing the challenges of life and family.'
            ],
            [
                'title' => 'Neon Genesis Evangelion',
                'japanese_title' => '新世紀エヴァンゲリオン',
                'poster' => 'p-neon-genesis-evangelion.jpg',
                'navbar_cover' => 'n-neon-genesis-evangelion.jpg',
                'genre' => 'Psychological, Sci-Fi, Mecha',
                'score' => 8.3,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 26,
                'duration' => '25 min per ep',
                'release_date' => '1995-10-04',
                'studio' => 'Gainax',
                'producer' => 'TV Tokyo',
                'synopsis' => 'Teenagers pilot giant mechs to protect humanity from mysterious beings.'
            ],
            [
                'title' => 'Cowboy Bebop',
                'japanese_title' => 'カウボーイビバップ',
                'poster' => 'p-cowboy-bebop.jpg',
                'navbar_cover' => 'n-cowboy-bebop.jpg',
                'genre' => 'Action, Sci-Fi, Space',
                'score' => 8.9,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 26,
                'duration' => '25 min per ep',
                'release_date' => '1998-04-03',
                'studio' => 'Sunrise',
                'producer' => 'Bandai Visual',
                'synopsis' => 'Bounty hunters in space pursue dangerous criminals while confronting their pasts.'
            ],
            [
                'title' => 'Spirited Away',
                'japanese_title' => '千と千尋の神隠し',
                'poster' => 'p-spirited-away.jpg',
                'navbar_cover' => 'n-spirited-away.jpg',
                'genre' => 'Adventure, Supernatural, Drama',
                'score' => 8.9,
                'type' => 'Movie',
                'status' => 'Finished Airing',
                'total_episode' => 1,
                'duration' => '125 min',
                'release_date' => '2001-07-20',
                'studio' => 'Studio Ghibli',
                'producer' => 'Tokuma Shoten',
                'synopsis' => 'A young girl finds herself in a strange world of spirits and must find her way home.'
            ],
            [
                'title' => 'Your Name',
                'japanese_title' => '君の名は。',
                'poster' => 'p-your-name.jpg',
                'navbar_cover' => 'n-your-name.jpg',
                'genre' => 'Romance, Supernatural, Drama',
                'score' => 9.1,
                'type' => 'Movie',
                'status' => 'Finished Airing',
                'total_episode' => 1,
                'duration' => '107 min',
                'release_date' => '2016-08-26',
                'studio' => 'CoMix Wave Films',
                'producer' => 'TOHO',
                'synopsis' => 'Two strangers find themselves mysteriously swapping bodies and embark on a journey to find each other.'
            ],
            [
                'title' => 'Tokyo Revengers',
                'japanese_title' => '東京リベンジャーズ',
                'poster' => 'p-tokyo-revengers.jpg',
                'navbar_cover' => 'n-tokyo-revengers.jpg',
                'genre' => 'Action, Drama, Supernatural',
                'score' => 8.3,
                'type' => 'TV',
                'status' => 'Ongoing',
                'total_episode' => 24,
                'duration' => '24 min per ep',
                'release_date' => '2021-04-11',
                'studio' => 'LIDENFILMS',
                'producer' => 'Crunchyroll',
                'synopsis' => 'A man travels back in time to save the girl he loved and fix the past.'
            ],
            [
                'title' => 'Steins;Gate',
                'japanese_title' => 'シュタインズ・ゲート',
                'poster' => 'p-steins-gate.jpg',
                'navbar_cover' => 'n-steins-gate.jpg',
                'genre' => 'Sci-Fi, Thriller, Drama',
                'score' => 9.0,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 24,
                'duration' => '24 min per ep',
                'release_date' => '2011-04-06',
                'studio' => 'White Fox',
                'producer' => 'Nitroplus',
                'synopsis' => 'A group of friends accidentally invent a time machine and face the consequences of tampering with time.'
            ],
            [
                'title' => 'Inuyasha',
                'japanese_title' => '犬夜叉',
                'poster' => 'p-inuyasha.jpg',
                'navbar_cover' => 'n-inuyasha.jpg',
                'genre' => 'Action, Adventure, Fantasy',
                'score' => 7.9,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 167,
                'duration' => '24 min per ep',
                'release_date' => '2000-10-16',
                'studio' => 'Sunrise',
                'producer' => 'Yomiuri Telecasting',
                'synopsis' => 'A high school girl and a half-demon embark on a quest to collect the shards of a sacred jewel.'

            ],
            [
                'title' => 'Erased',
                'japanese_title' => '僕だけがいない街',
                'poster' => 'p-erased.jpg',
                'navbar_cover' => 'n-erased.jpg',
                'genre' => 'Mystery, Supernatural, Thriller',
                'score' => 8.5,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 12,
                'duration' => '23 min per ep',
                'release_date' => '2016-01-08',
                'studio' => 'A-1 Pictures',
                'producer' => 'Aniplex',
                'synopsis' => 'A man with a unique ability travels back in time to prevent a series of murders.'
            ],
            [
                'title' => 'Twin Star Exorcists',
                'japanese_title' => '双星の陰陽師',
                'poster' => 'p-twin-star-exorcists.jpg',
                'navbar_cover' => 'n-twin-star-exorcists.jpg',
                'genre' => 'Action, Supernatural, Fantasy',
                'score' => 7.4,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 50,
                'duration' => '24 min per ep',
                'release_date' => '2016-04-06',
                'studio' => 'Pierrot',
                'producer' => 'TV Tokyo',
                'synopsis' => 'Two young exorcists with contrasting personalities must work together to rid the world of evil spirits.'
            ],
            [
                'title' => 'Gintama',
                'japanese_title' => '銀魂',
                'poster' => 'p-gintama.jpg',
                'navbar_cover' => 'n-gintama.jpg',
                'genre' => 'Action, Comedy, Sci-Fi',
                'score' => 8.9,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 367,
                'duration' => '24 min per ep',
                'release_date' => '2006-04-04',
                'studio' => 'Sunrise',
                'producer' => 'TV Tokyo',
                'synopsis' => 'In an alternate Edo period, a samurai and his friends take on odd jobs and fight aliens.'
            ],
            [
                'title' => 'Daily Lives of High School Boys',
                'japanese_title' => '男子高校生の日常',
                'poster' => 'p-danshi-koukousei-no-nichijou.jpg',
                'navbar_cover' => 'n-danshi-koukousei-no-nichijou.jpg',
                'genre' => 'Comedy, Slice of Life, School',
                'score' => 8.2,
                'type' => 'TV',
                'status' => 'Finished Airing',
                'total_episode' => 12,
                'duration' => '24 min per ep',
                'release_date' => '2012-01-10',
                'studio' => 'Sunrise',
                'producer' => 'Square Enix',
                'synopsis' => 'A hilarious portrayal of the everyday lives of high school boys with absurd humor.'
            ]
        ];
        $this->db->table('anime')->insertBatch($data);
    }
}